apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    type: nginx
    app: myapp
spec:
  selector:
    matchLabels:
      type: nginx
      app: myapp
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        type: nginx
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"