apiVersion: v1 
kind: Pod 
metadata: 
  name: helloworld-v1
  labels: 
    creation_method: manual 
    env: prod
spec:
  containers:
    - image: gianglt1/helloworld
      name: helloworld
      ports:
      - containerPort: 3333
        protocol: TCP
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"