apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
    - image: tamle6099/helloworld
      name: helloworld
      ports:
        - containerPort: 3333
          protocol: TCP
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
