# Use root/example as user/password credentials
version: "3.1"

services:
  socat:
    # platform: linux/x86_64
    image: alpine/socat
    network_mode: bridge
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    restart: always
    ports:
      - 2377:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: socat_docker
