apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
	name: cluster-jenkins-role-binding
subjects:
	- kind: User
		name: jenkins
		apiGroup: rbac.authorization.k8s.io
roleRef:
	kind: ClusterRole
	name: jenkins-role
	apiGroup: rbac.authorization.k8s.io