apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    name: helloworld-deployment
    app: helloworld-app
spec:
  selector:
    matchLabels:
      name: helloworld-pod
      app: helloworld-app
  template:
    metadata:
      name: helloworld-pod
      labels:
        name: helloworld-pod
        app: helloworld-app
    spec:
      containers:
        - name: helloworld-app
          image: tamle6099/helloworld
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3333

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    name: helloworld-service
    app: helloworld-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 3333
      port: 3333
  selector:
    name: helloworld-pod
    app: helloworld-app
