apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    name: voting-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-pod
      app: demo-voting-app
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  # type: NodePort
  # ports:
  #   - port: 80
  #     targetPort: 80
  #     nodePort: 30004
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: voting-pod
    app: demo-voting-app